---

###
### Travis settings
###
sudo: required
services:
  - docker


jobs:
  include:
    ###
    ### Stage 1: Static file analysis
    ###
    - stage: static file analysis
      install:
        # Repeat "apt-get update" multiple times in case of network issues
        - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get update; then break; else i=$((i+1)); fi done
        # Repeat "apt-get install" multiple times in case of network issues
        - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get -y install moreutils; then break; else i=$((i+1)); fi done
        - git clone https://github.com/Flaconi/awesome-ci /tmp/awesome-ci
        - sh -c "cd /tmp/awesome-ci && ./configure --prefix=/usr/local && sudo make install"
      script:
        - ./tests/static-file-checks.sh

    ###
    ### Stage 2: Build, Test and Deploy
    ###

    # [Stage 2] [Job 1]
    - stage: build and deploy
      env: java=stretch-slim-openjdk-java8
      install:
        - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get update; then break; else i=$((i+1)); fi done
        - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce; then break; else i=$((i+1)); fi done
      before_script:
        - make build TAG="${java}"
        - make test  TAG="${java}" VERSION=8
      script:
        - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
            make login USER="${DOCKERHUB_USERNAME}" PASS="${DOCKERHUB_PASSWORD}";
            if [ "${TRAVIS_BRANCH}" == "master" ]; then
              make push TAG="${java}";
            elif [ -n "${TRAVIS_TAG}" ]; then
              make tag  TAG="${java}" NEW_TAG="${java}-${TRAVIS_TAG}";
              make push TAG="${java}-${TRAVIS_TAG}";
            else
              echo "Skipping push to dockerhub on normal branches";
            fi
          else
            echo "Skipping push to dockerhub on PR";
          fi
