---

###
### Travis settings
###
sudo: required
services:
  - docker


###
### Env variables
###
env:
  global:
    - image=flaconi/java-base

jobs:
  include:
    ###
    ### Stage 1: Static file analysis
    ###
    - stage: static file analysis
      install:
        - git clone https://github.com/cytopia/awesome-ci /tmp/awesome-ci
        - cd /tmp/awesome-ci && ./configure --prefix=/usr/local && make install
      script:
        - ./tests/static-file-checks.sh

    ###
    ### Stage 2: Build, Test and Deploy
    ###

    # [Stage 2] [Job 1]
    - stage: build and deploy
      env: java=stretch-oracle-java8
      install:
        - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get update; then break; else i=$((i+1)); fi done
        - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce; then break; else i=$((i+1)); fi done
      script:
        - ./tests/build.sh "${image}" "${java}"
        - ./tests/check.sh "${image}" "${java}" "8"
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
              if [ "${TRAVIS_BRANCH}" == "master" ]; then
                echo "[NOP] docker push ${image}:${java}";
              elif [ -n "${TRAVIS_TAG}" ]; then
                echo "[NOP] docker tag ${image}:${java} ${image}:${java}-${TRAVIS_TAG}";
                echo "[NOP] docker push ${image}:${java}-${TRAVIS_TAG}";
              else
                echo "Skipping push to dockerhub on normal branches";
              fi
            else
              echo "Skipping push to dockerhub on PR";
            fi

    # [Stage 2] [Job 2]
    - stage: build and deploy
      env: java=stretch-oracle-java9
      install:
        - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get update; then break; else i=$((i+1)); fi done
        - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce; then break; else i=$((i+1)); fi done
      script:
        - ./tests/build.sh "${image}" "${java}"
        - ./tests/check.sh "${image}" "${java}" "9"
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
              if [ "${TRAVIS_BRANCH}" == "master" ]; then
                echo "[NOP] docker push ${image}:${java}";
              elif [ -n "${TRAVIS_TAG}" ]; then
                echo "[NOP] docker tag ${image}:${java} ${image}:${java}-${TRAVIS_TAG}";
                echo "[NOP] docker push ${image}:${java}-${TRAVIS_TAG}";
              else
                echo "Skipping push to dockerhub on normal branches";
              fi
            else
              echo "Skipping push to dockerhub on PR";
            fi
